In [108]:
import pandas as pd

In [109]:
resultater_partier = pd.read_csv("data/struktureret/resultater_partier.csv")
res_opstillingskreds_2022 = pd.read_csv("data/resultater_2022/processed/opstillingskreds_resultater.csv")

In [110]:
parti = "O"
parti1 = "DF"

In [111]:
# filter resultater_partier to only include rows where parti is "O"
df = resultater_partier[resultater_partier["parti_bogstav"] == parti]

In [112]:
df = df.groupby(['opstillingskreds_dagi_id',"opstillingskreds"]).agg({"stemmer": "sum",
                                                                "total_gyldige_stemmer":"sum"}).reset_index()

In [113]:
df['procent_26'] = (round(df['stemmer'] / df['total_gyldige_stemmer'] * 100,1))

In [114]:
df

,opstillingskreds_dagi_id,opstillingskreds,stemmer,total_gyldige_stemmer,procent_26
0,403550,Rønne,1291,11910,10.8
1,403551,Aakirkeby,1209,11824,10.2
2,403552,Helsingør,3825,39134,9.8
3,403553,Egedal,4596,53802,8.5
4,403554,Fredensborg,3389,40838,8.3
...,...,...,...,...,...
87,403637,Faxe,6859,38400,17.9
88,403638,Guldborgsund,5321,36460,14.6
89,403639,Lolland,3478,22498,15.5
90,403640,Vejle Syd,3549,36010,9.9
91,403641,Vejle Nord,3189,35259,9.0

In [115]:
res_opstillingskreds_2022
res_opstillingskreds_2022 = res_opstillingskreds_2022[res_opstillingskreds_2022["Partibogstav"] == parti1]

In [116]:
res_opstillingskreds_2022

,opstillingskreds_dagi,Opstillingskreds,Partibogstav,Stemmetal,procent_22
2,403550,Rønne,DF,811,6.7
16,403551,Aakirkeby,DF,739,6.1
30,403552,Helsingør,DF,964,2.5
44,403553,Egedal,DF,1321,2.5
58,403554,Fredensborg,DF,916,2.3
...,...,...,...,...,...
1220,403637,Faxe,DF,1680,4.5
1234,403638,Guldborgsund,DF,3308,8.8
1248,403639,Lolland,DF,1392,5.8
1262,403640,Vejle Syd,DF,759,2.1
1276,403641,Vejle Nord,DF,690,2.0

In [117]:
#join df and res_opstillingskreds_2022 on opstillingskreds_dagi_id and opstillingskreds_dagi
df_joined = pd.merge(df, res_opstillingskreds_2022, left_on='opstillingskreds_dagi_id', right_on='opstillingskreds_dagi', how='left')

In [118]:
df_joined = df_joined[["opstillingskreds_dagi_id", "opstillingskreds", "procent_26", "procent_22"]]

In [119]:
df_joined['diff_procent'] = df_joined['procent_26'] - df_joined['procent_22']

In [121]:
df_joined

,opstillingskreds_dagi_id,opstillingskreds,procent_26,procent_22,diff_procent
0,403550,Rønne,10.8,6.7,4.1
1,403551,Aakirkeby,10.2,6.1,4.1
2,403552,Helsingør,9.8,2.5,7.3
3,403553,Egedal,8.5,2.5,6.0
4,403554,Fredensborg,8.3,2.3,6.0
...,...,...,...,...,...
87,403637,Faxe,17.9,4.5,13.4
88,403638,Guldborgsund,14.6,8.8,5.8
89,403639,Lolland,15.5,5.8,9.7
90,403640,Vejle Syd,9.9,2.1,7.8
91,403641,Vejle Nord,9.0,2.0,7.0

In [120]:
df_joined.to_clipboard(index=False)