In [309]:
import pandas as pd

In [310]:
resultater_partier = pd.read_csv("data/struktureret/resultater_partier.csv")
res_opstillingskreds_2022 = pd.read_csv("data/resultater_2022/processed/opstillingskreds_resultater.csv")

In [311]:
parti = "Æ"
parti1 = "DD"

In [312]:
# filter resultater_partier to only include rows where parti is "O"
df = resultater_partier[resultater_partier["parti_bogstav"] == parti]

In [313]:
df = df.groupby(['opstillingskreds_dagi_id',"opstillingskreds"]).agg({"stemmer": "sum",
                                                                "total_gyldige_stemmer":"sum"}).reset_index()

In [314]:
df['procent_26'] = (round(df['stemmer'] / df['total_gyldige_stemmer'] * 100,1))

In [315]:
df

,opstillingskreds_dagi_id,opstillingskreds,stemmer,total_gyldige_stemmer,procent_26
0,403550,Rønne,453,11910,3.8
1,403551,Aakirkeby,547,11824,4.6
2,403552,Helsingør,939,39134,2.4
3,403553,Egedal,985,53802,1.8
4,403554,Fredensborg,609,40838,1.5
...,...,...,...,...,...
87,403637,Faxe,2263,38400,5.9
88,403638,Guldborgsund,2885,36460,7.9
89,403639,Lolland,2999,22498,13.3
90,403640,Vejle Syd,1965,36010,5.5
91,403641,Vejle Nord,2597,35259,7.4

In [316]:
res_opstillingskreds_2022
res_opstillingskreds_2022 = res_opstillingskreds_2022[res_opstillingskreds_2022["Partibogstav"] == parti1]

In [317]:
res_opstillingskreds_2022

,opstillingskreds_dagi,Opstillingskreds,Partibogstav,Stemmetal,procent_22
12,403550,Rønne,DD,1456,5.9
26,403551,Aakirkeby,DD,1724,6.9
40,403552,Helsingør,DD,3632,4.7
54,403553,Egedal,DD,4250,4.0
68,403554,Fredensborg,DD,2910,3.6
...,...,...,...,...,...
1230,403637,Faxe,DD,7888,10.5
1244,403638,Guldborgsund,DD,6622,8.8
1258,403639,Lolland,DD,4988,10.4
1272,403640,Vejle Syd,DD,6280,8.8
1286,403641,Vejle Nord,DD,7268,10.5

In [318]:
#join df and res_opstillingskreds_2022 on opstillingskreds_dagi_id and opstillingskreds_dagi
df_joined = pd.merge(df, res_opstillingskreds_2022, left_on='opstillingskreds_dagi_id', right_on='opstillingskreds_dagi', how='left')

In [319]:
df_joined = df_joined[["opstillingskreds_dagi_id", "opstillingskreds", "procent_26", "procent_22"]]

In [320]:
df_joined['diff_procent'] = round(df_joined['procent_26'] - df_joined['procent_22'],1)

In [321]:
df_joined = df_joined.sort_values(by='diff_procent', ascending=False)

In [307]:
# # keep the first 10 and last 10 rows
# df_joined = pd.concat([df_joined.head(10), df_joined.tail(10)])

# # set cat to top for the first 10 rows and cat to bottom for the last 10 rows
# df_joined['cat'] = ['top'] * 10 + ['bottom'] * 10

In [322]:
df_joined.to_clipboard(index=False)